name: Test and Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest --cov=markdown_inspector --cov-report=xml --cov-report=term

    - name: Check coverage threshold
      run: |
        coverage_value=$(python -c "import xml.etree.ElementTree as ET; root = ET.parse('coverage.xml').getroot(); print(float(root.get('line-rate')) * 100)")
        echo "Coverage: $coverage_value%"
        if (( $(echo "$coverage_value < 80" | bc -l) )); then
          echo "Coverage below threshold of 80%"
          exit 1
        fi

    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Build package
      if: success()
      run: |
        pip install build
        python -m build

    - name: Upload package artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: markdown-inspector-package
        path: dist/